name: jest
on: [push, pull_request]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: 16
      - uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install
        run: yarn install
      - name: standard
        run: yarn standard
      - name: jest
        run: yarn test
